//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemaModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchemaModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*
        ///Copyright by:
        ///International Alliance for Interoperability, 1996-2007
        ///
        ///All rights reserved. No part of this documentation may be
        ///reproduced, stored in a retrieval system, or transmitted
        ///in any form or by any means, without the prior written
        ///permission of the owner.
        ///
        ///Contents:
        ///full IFC object model EXPRESS definitions for the IFC2x Edition 3 Technical Corrigendum 1 release
        ///
        ///- express longform distribution
        ///- compiled for EXPRESS version 1 technical corrigendum 2
        ///
        ///Issue date:
        ///July 10, 2007
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IFC2X3 {
            get {
                return ResourceManager.GetString("IFC2X3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*
        ///Copyright by:
        ///buildingSMART International Ltd, 1996-2013
        ///Any technical documentation made available by buildingSMART International Limited 
        ///is the copyrighted work of buildingSMART International Limited and is owned by the 
        ///buildingSMART International Limited. It may be photocopied, used in software development, 
        ///or translated into another computer language without prior written consent from 
        ///buildingSMART International Limited provided that full attribution is given. 
        ///Prior written consent is re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IFC4 {
            get {
                return ResourceManager.GetString("IFC4", resourceCulture);
            }
        }
    }
}
