//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BlackBox", "BbHierarchy", "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbDefinition), "BbDefinitionOfSubTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BlackBox.BbDefinition), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "SEntityBbDefinition", "SEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.SEntity), "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbDefinition))]
[assembly: EdmRelationshipAttribute("BlackBox", "EntityAttributeBbDefinition", "EntityAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.EntityAttribute), "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BlackBox.BbDefinition), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "EntityAttributeSEntity", "EntityAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.EntityAttribute), "SEntity", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BlackBox.SEntity), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "BbTypeAttributeBbDefinition", "BbTypeAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbTypeAttribute), "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlackBox.BbDefinition), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "BbTypeForAttribute", "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlackBox.BbDefinition), "BbTypeAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbTypeAttribute), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "NameSpaceAciExchange", "NameSpace", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlackBox.NameSpace), "AciExchange", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.MvdExchange), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "AciExchangeMvdDefinition", "AciExchange", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlackBox.MvdExchange), "MvdDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.MvdDefinition), true)]
[assembly: EdmRelationshipAttribute("BlackBox", "BbDefinitionNameSpace", "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbDefinition), "NameSpace", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.NameSpace))]
[assembly: EdmRelationshipAttribute("BlackBox", "BbDefinitionNameSpace1", "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbDefinition), "NameSpace", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.NameSpace))]
[assembly: EdmRelationshipAttribute("BlackBox", "BbDefinitionBbDefinition", "BbDefinition", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BlackBox.BbDefinition), "BbDefinition1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlackBox.BbDefinition), true)]

#endregion

namespace BlackBox
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BbContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BbContainer object using the connection string found in the 'BbContainer' section of the application configuration file.
        /// </summary>
        public BbContainer() : base("name=BbContainer", "BbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BbContainer object.
        /// </summary>
        public BbContainer(string connectionString) : base(connectionString, "BbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BbContainer object.
        /// </summary>
        public BbContainer(EntityConnection connection) : base(connection, "BbContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Definition> Definitions
        {
            get
            {
                if ((_Definitions == null))
                {
                    _Definitions = base.CreateObjectSet<Definition>("Definitions");
                }
                return _Definitions;
            }
        }
        private ObjectSet<Definition> _Definitions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MvdExchange> MvdExchanges
        {
            get
            {
                if ((_MvdExchanges == null))
                {
                    _MvdExchanges = base.CreateObjectSet<MvdExchange>("MvdExchanges");
                }
                return _MvdExchanges;
            }
        }
        private ObjectSet<MvdExchange> _MvdExchanges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NameSpace> NameSpaces
        {
            get
            {
                if ((_NameSpaces == null))
                {
                    _NameSpaces = base.CreateObjectSet<NameSpace>("NameSpaces");
                }
                return _NameSpaces;
            }
        }
        private ObjectSet<NameSpace> _NameSpaces;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Definitions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDefinitions(Definition definition)
        {
            base.AddObject("Definitions", definition);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MvdExchanges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMvdExchanges(MvdExchange mvdExchange)
        {
            base.AddObject("MvdExchanges", mvdExchange);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NameSpaces EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNameSpaces(NameSpace nameSpace)
        {
            base.AddObject("NameSpaces", nameSpace);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="AttributeDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(EntityAttribute))]
    [KnownTypeAttribute(typeof(BbTypeAttribute))]
    public partial class AttributeDefinition : Definition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AttributeDefinition object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="dataType">Initial value of the DataType property.</param>
        public static AttributeDefinition CreateAttributeDefinition(global::System.Guid guid, global::System.String name, global::System.String dataType)
        {
            AttributeDefinition attributeDefinition = new AttributeDefinition();
            attributeDefinition.Guid = guid;
            attributeDefinition.Name = name;
            attributeDefinition.DataType = dataType;
            return attributeDefinition;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataType
        {
            get
            {
                return _DataType;
            }
            set
            {
                OnDataTypeChanging(value);
                ReportPropertyChanging("DataType");
                _DataType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataType");
                OnDataTypeChanged();
            }
        }
        private global::System.String _DataType;
        partial void OnDataTypeChanging(global::System.String value);
        partial void OnDataTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LowerBound
        {
            get
            {
                return _LowerBound;
            }
            set
            {
                OnLowerBoundChanging(value);
                ReportPropertyChanging("LowerBound");
                _LowerBound = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LowerBound");
                OnLowerBoundChanged();
            }
        }
        private global::System.Int16 _LowerBound = 1;
        partial void OnLowerBoundChanging(global::System.Int16 value);
        partial void OnLowerBoundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 UpperBound
        {
            get
            {
                return _UpperBound;
            }
            set
            {
                OnUpperBoundChanging(value);
                ReportPropertyChanging("UpperBound");
                _UpperBound = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpperBound");
                OnUpperBoundChanged();
            }
        }
        private global::System.Int16 _UpperBound = 1;
        partial void OnUpperBoundChanging(global::System.Int16 value);
        partial void OnUpperBoundChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="BbDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BbDefinition : Definition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BbDefinition object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="creator">Initial value of the Creator property.</param>
        public static BbDefinition CreateBbDefinition(global::System.Guid guid, global::System.String name, global::System.DateTime creationDate, global::System.String creator)
        {
            BbDefinition bbDefinition = new BbDefinition();
            bbDefinition.Guid = guid;
            bbDefinition.Name = name;
            bbDefinition.CreationDate = creationDate;
            bbDefinition.Creator = creator;
            return bbDefinition;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                OnCreatorChanging(value);
                ReportPropertyChanging("Creator");
                _Creator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Creator");
                OnCreatorChanged();
            }
        }
        private global::System.String _Creator;
        partial void OnCreatorChanging(global::System.String value);
        partial void OnCreatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FkSuperTypeGuid
        {
            get
            {
                return _FkSuperTypeGuid;
            }
            set
            {
                OnFkSuperTypeGuidChanging(value);
                ReportPropertyChanging("FkSuperTypeGuid");
                _FkSuperTypeGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkSuperTypeGuid");
                OnFkSuperTypeGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _FkSuperTypeGuid;
        partial void OnFkSuperTypeGuidChanging(Nullable<global::System.Guid> value);
        partial void OnFkSuperTypeGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FkCompositionGuid
        {
            get
            {
                return _FkCompositionGuid;
            }
            set
            {
                OnFkCompositionGuidChanging(value);
                ReportPropertyChanging("FkCompositionGuid");
                _FkCompositionGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkCompositionGuid");
                OnFkCompositionGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _FkCompositionGuid;
        partial void OnFkCompositionGuidChanging(Nullable<global::System.Guid> value);
        partial void OnFkCompositionGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbHierarchy", "BbDefinitionOfSubTypes")]
        public BbDefinition SuperType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbHierarchy", "BbDefinitionOfSubTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbHierarchy", "BbDefinitionOfSubTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BbDefinition> SuperTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbHierarchy", "BbDefinitionOfSubTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BbDefinition>("BlackBox.BbHierarchy", "BbDefinitionOfSubTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbHierarchy", "BbDefinition")]
        public EntityCollection<BbDefinition> SubTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbDefinition>("BlackBox.BbHierarchy", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbDefinition>("BlackBox.BbHierarchy", "BbDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "SEntityBbDefinition", "SEntity")]
        public EntityCollection<SEntity> SEntities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SEntity>("BlackBox.SEntityBbDefinition", "SEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SEntity>("BlackBox.SEntityBbDefinition", "SEntity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "EntityAttributeBbDefinition", "EntityAttribute")]
        public EntityCollection<EntityAttribute> EntityAttributes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityAttribute>("BlackBox.EntityAttributeBbDefinition", "EntityAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityAttribute>("BlackBox.EntityAttributeBbDefinition", "EntityAttribute", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbTypeAttributeBbDefinition", "BbTypeAttribute")]
        public EntityCollection<BbTypeAttribute> BbTypeAttributes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbTypeAttribute>("BlackBox.BbTypeAttributeBbDefinition", "BbTypeAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbTypeAttribute>("BlackBox.BbTypeAttributeBbDefinition", "BbTypeAttribute", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbTypeForAttribute", "BbTypeAttribute")]
        public EntityCollection<BbTypeAttribute> UsedInAttributes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbTypeAttribute>("BlackBox.BbTypeForAttribute", "BbTypeAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbTypeAttribute>("BlackBox.BbTypeForAttribute", "BbTypeAttribute", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbDefinitionNameSpace", "NameSpace")]
        public EntityCollection<NameSpace> NameSpaces
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NameSpace>("BlackBox.BbDefinitionNameSpace", "NameSpace");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NameSpace>("BlackBox.BbDefinitionNameSpace", "NameSpace", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbDefinitionNameSpace1", "NameSpace")]
        public EntityCollection<NameSpace> RootBbsInNS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NameSpace>("BlackBox.BbDefinitionNameSpace1", "NameSpace");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NameSpace>("BlackBox.BbDefinitionNameSpace1", "NameSpace", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbDefinitionBbDefinition", "BbDefinition1")]
        public EntityCollection<BbDefinition> BbComposition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbDefinition>("BlackBox.BbDefinitionBbDefinition", "BbDefinition1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbDefinition>("BlackBox.BbDefinitionBbDefinition", "BbDefinition1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="BbTypeAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BbTypeAttribute : AttributeDefinition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BbTypeAttribute object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="dataType">Initial value of the DataType property.</param>
        /// <param name="fkBbGuidInAttributes">Initial value of the FkBbGuidInAttributes property.</param>
        /// <param name="fkBbDefinitionGuid">Initial value of the FkBbDefinitionGuid property.</param>
        public static BbTypeAttribute CreateBbTypeAttribute(global::System.Guid guid, global::System.String name, global::System.String dataType, global::System.Guid fkBbGuidInAttributes, global::System.Guid fkBbDefinitionGuid)
        {
            BbTypeAttribute bbTypeAttribute = new BbTypeAttribute();
            bbTypeAttribute.Guid = guid;
            bbTypeAttribute.Name = name;
            bbTypeAttribute.DataType = dataType;
            bbTypeAttribute.FkBbGuidInAttributes = fkBbGuidInAttributes;
            bbTypeAttribute.FkBbDefinitionGuid = fkBbDefinitionGuid;
            return bbTypeAttribute;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FkBbGuidInAttributes
        {
            get
            {
                return _FkBbGuidInAttributes;
            }
            set
            {
                OnFkBbGuidInAttributesChanging(value);
                ReportPropertyChanging("FkBbGuidInAttributes");
                _FkBbGuidInAttributes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkBbGuidInAttributes");
                OnFkBbGuidInAttributesChanged();
            }
        }
        private global::System.Guid _FkBbGuidInAttributes;
        partial void OnFkBbGuidInAttributesChanging(global::System.Guid value);
        partial void OnFkBbGuidInAttributesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FkBbDefinitionGuid
        {
            get
            {
                return _FkBbDefinitionGuid;
            }
            set
            {
                OnFkBbDefinitionGuidChanging(value);
                ReportPropertyChanging("FkBbDefinitionGuid");
                _FkBbDefinitionGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkBbDefinitionGuid");
                OnFkBbDefinitionGuidChanged();
            }
        }
        private global::System.Guid _FkBbDefinitionGuid;
        partial void OnFkBbDefinitionGuidChanging(global::System.Guid value);
        partial void OnFkBbDefinitionGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbTypeAttributeBbDefinition", "BbDefinition")]
        public BbDefinition BbBelongsTo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeAttributeBbDefinition", "BbDefinition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeAttributeBbDefinition", "BbDefinition").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BbDefinition> BbBelongsToReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeAttributeBbDefinition", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BbDefinition>("BlackBox.BbTypeAttributeBbDefinition", "BbDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbTypeForAttribute", "BbDefinition")]
        public BbDefinition BbTypeOfAttribute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeForAttribute", "BbDefinition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeForAttribute", "BbDefinition").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BbDefinition> BbTypeOfAttributeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.BbTypeForAttribute", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BbDefinition>("BlackBox.BbTypeForAttribute", "BbDefinition", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="Definition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(BbDefinition))]
    [KnownTypeAttribute(typeof(SEntity))]
    [KnownTypeAttribute(typeof(AttributeDefinition))]
    [KnownTypeAttribute(typeof(MvdDefinition))]
    public partial class Definition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Definition object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Definition CreateDefinition(global::System.Guid guid, global::System.String name)
        {
            Definition definition = new Definition();
            definition.Guid = guid;
            definition.Name = name;
            return definition;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InterpretedName
        {
            get
            {
                return _InterpretedName;
            }
            set
            {
                OnInterpretedNameChanging(value);
                ReportPropertyChanging("InterpretedName");
                _InterpretedName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InterpretedName");
                OnInterpretedNameChanged();
            }
        }
        private global::System.String _InterpretedName;
        partial void OnInterpretedNameChanging(global::System.String value);
        partial void OnInterpretedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="EntityAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityAttribute : AttributeDefinition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityAttribute object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="dataType">Initial value of the DataType property.</param>
        public static EntityAttribute CreateEntityAttribute(global::System.Guid guid, global::System.String name, global::System.String dataType)
        {
            EntityAttribute entityAttribute = new EntityAttribute();
            entityAttribute.Guid = guid;
            entityAttribute.Name = name;
            entityAttribute.DataType = dataType;
            return entityAttribute;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IfcEntityAttribute
        {
            get
            {
                return _IfcEntityAttribute;
            }
            set
            {
                OnIfcEntityAttributeChanging(value);
                ReportPropertyChanging("IfcEntityAttribute");
                _IfcEntityAttribute = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IfcEntityAttribute");
                OnIfcEntityAttributeChanged();
            }
        }
        private global::System.String _IfcEntityAttribute;
        partial void OnIfcEntityAttributeChanging(global::System.String value);
        partial void OnIfcEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FkBbDefinitionGuid
        {
            get
            {
                return _FkBbDefinitionGuid;
            }
            set
            {
                OnFkBbDefinitionGuidChanging(value);
                ReportPropertyChanging("FkBbDefinitionGuid");
                _FkBbDefinitionGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkBbDefinitionGuid");
                OnFkBbDefinitionGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _FkBbDefinitionGuid;
        partial void OnFkBbDefinitionGuidChanging(Nullable<global::System.Guid> value);
        partial void OnFkBbDefinitionGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FkSEntityGuid
        {
            get
            {
                return _FkSEntityGuid;
            }
            set
            {
                OnFkSEntityGuidChanging(value);
                ReportPropertyChanging("FkSEntityGuid");
                _FkSEntityGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FkSEntityGuid");
                OnFkSEntityGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _FkSEntityGuid;
        partial void OnFkSEntityGuidChanging(Nullable<global::System.Guid> value);
        partial void OnFkSEntityGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "EntityAttributeBbDefinition", "BbDefinition")]
        public BbDefinition BbDefinition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.EntityAttributeBbDefinition", "BbDefinition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.EntityAttributeBbDefinition", "BbDefinition").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BbDefinition> BbDefinitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BbDefinition>("BlackBox.EntityAttributeBbDefinition", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BbDefinition>("BlackBox.EntityAttributeBbDefinition", "BbDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "EntityAttributeSEntity", "SEntity")]
        public SEntity SEntity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEntity>("BlackBox.EntityAttributeSEntity", "SEntity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEntity>("BlackBox.EntityAttributeSEntity", "SEntity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SEntity> SEntityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEntity>("BlackBox.EntityAttributeSEntity", "SEntity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SEntity>("BlackBox.EntityAttributeSEntity", "SEntity", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="MvdDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MvdDefinition : Definition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MvdDefinition object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        /// <param name="mvdExchangeGuid">Initial value of the MvdExchangeGuid property.</param>
        public static MvdDefinition CreateMvdDefinition(global::System.Guid guid, global::System.String name, global::System.Boolean isDeleted, global::System.Guid mvdExchangeGuid)
        {
            MvdDefinition mvdDefinition = new MvdDefinition();
            mvdDefinition.Guid = guid;
            mvdDefinition.Name = name;
            mvdDefinition.IsDeleted = isDeleted;
            mvdDefinition.MvdExchangeGuid = mvdExchangeGuid;
            return mvdDefinition;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                OnCreatorChanging(value);
                ReportPropertyChanging("Creator");
                _Creator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Creator");
                OnCreatorChanged();
            }
        }
        private global::System.String _Creator;
        partial void OnCreatorChanging(global::System.String value);
        partial void OnCreatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private Nullable<global::System.Int32> _Version;
        partial void OnVersionChanging(Nullable<global::System.Int32> value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Boolean _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Boolean value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String definition
        {
            get
            {
                return _definition;
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.String _definition;
        partial void OndefinitionChanging(global::System.String value);
        partial void OndefinitionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MvdExchangeGuid
        {
            get
            {
                return _MvdExchangeGuid;
            }
            set
            {
                OnMvdExchangeGuidChanging(value);
                ReportPropertyChanging("MvdExchangeGuid");
                _MvdExchangeGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MvdExchangeGuid");
                OnMvdExchangeGuidChanged();
            }
        }
        private global::System.Guid _MvdExchangeGuid;
        partial void OnMvdExchangeGuidChanging(global::System.Guid value);
        partial void OnMvdExchangeGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "AciExchangeMvdDefinition", "AciExchange")]
        public MvdExchange MvdExchange
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MvdExchange>("BlackBox.AciExchangeMvdDefinition", "AciExchange").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MvdExchange>("BlackBox.AciExchangeMvdDefinition", "AciExchange").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MvdExchange> MvdExchangeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MvdExchange>("BlackBox.AciExchangeMvdDefinition", "AciExchange");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MvdExchange>("BlackBox.AciExchangeMvdDefinition", "AciExchange", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="MvdExchange")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MvdExchange : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MvdExchange object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="ofInterest">Initial value of the OfInterest property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        /// <param name="nameSpaceGuid">Initial value of the NameSpaceGuid property.</param>
        public static MvdExchange CreateMvdExchange(global::System.Guid guid, global::System.String title, global::System.Boolean ofInterest, global::System.Boolean isDeleted, global::System.Guid nameSpaceGuid)
        {
            MvdExchange mvdExchange = new MvdExchange();
            mvdExchange.Guid = guid;
            mvdExchange.Title = title;
            mvdExchange.OfInterest = ofInterest;
            mvdExchange.IsDeleted = isDeleted;
            mvdExchange.NameSpaceGuid = nameSpaceGuid;
            return mvdExchange;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExchangeMaker
        {
            get
            {
                return _ExchangeMaker;
            }
            set
            {
                OnExchangeMakerChanging(value);
                ReportPropertyChanging("ExchangeMaker");
                _ExchangeMaker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExchangeMaker");
                OnExchangeMakerChanged();
            }
        }
        private global::System.String _ExchangeMaker;
        partial void OnExchangeMakerChanging(global::System.String value);
        partial void OnExchangeMakerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmNumber
        {
            get
            {
                return _EmNumber;
            }
            set
            {
                OnEmNumberChanging(value);
                ReportPropertyChanging("EmNumber");
                _EmNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmNumber");
                OnEmNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _EmNumber;
        partial void OnEmNumberChanging(Nullable<global::System.Int32> value);
        partial void OnEmNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProjectStage
        {
            get
            {
                return _ProjectStage;
            }
            set
            {
                OnProjectStageChanging(value);
                ReportPropertyChanging("ProjectStage");
                _ProjectStage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProjectStage");
                OnProjectStageChanged();
            }
        }
        private global::System.String _ProjectStage;
        partial void OnProjectStageChanging(global::System.String value);
        partial void OnProjectStageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Disciplines
        {
            get
            {
                return _Disciplines;
            }
            set
            {
                OnDisciplinesChanging(value);
                ReportPropertyChanging("Disciplines");
                _Disciplines = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Disciplines");
                OnDisciplinesChanged();
            }
        }
        private global::System.String _Disciplines;
        partial void OnDisciplinesChanging(global::System.String value);
        partial void OnDisciplinesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiscriptionPurpose
        {
            get
            {
                return _DiscriptionPurpose;
            }
            set
            {
                OnDiscriptionPurposeChanging(value);
                ReportPropertyChanging("DiscriptionPurpose");
                _DiscriptionPurpose = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiscriptionPurpose");
                OnDiscriptionPurposeChanged();
            }
        }
        private global::System.String _DiscriptionPurpose;
        partial void OnDiscriptionPurposeChanging(global::System.String value);
        partial void OnDiscriptionPurposeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionIncludes
        {
            get
            {
                return _DescriptionIncludes;
            }
            set
            {
                OnDescriptionIncludesChanging(value);
                ReportPropertyChanging("DescriptionIncludes");
                _DescriptionIncludes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionIncludes");
                OnDescriptionIncludesChanged();
            }
        }
        private global::System.String _DescriptionIncludes;
        partial void OnDescriptionIncludesChanging(global::System.String value);
        partial void OnDescriptionIncludesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionDetail
        {
            get
            {
                return _DescriptionDetail;
            }
            set
            {
                OnDescriptionDetailChanging(value);
                ReportPropertyChanging("DescriptionDetail");
                _DescriptionDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionDetail");
                OnDescriptionDetailChanged();
            }
        }
        private global::System.String _DescriptionDetail;
        partial void OnDescriptionDetailChanging(global::System.String value);
        partial void OnDescriptionDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionMajor
        {
            get
            {
                return _DescriptionMajor;
            }
            set
            {
                OnDescriptionMajorChanging(value);
                ReportPropertyChanging("DescriptionMajor");
                _DescriptionMajor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionMajor");
                OnDescriptionMajorChanged();
            }
        }
        private global::System.String _DescriptionMajor;
        partial void OnDescriptionMajorChanging(global::System.String value);
        partial void OnDescriptionMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionSpecial
        {
            get
            {
                return _DescriptionSpecial;
            }
            set
            {
                OnDescriptionSpecialChanging(value);
                ReportPropertyChanging("DescriptionSpecial");
                _DescriptionSpecial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionSpecial");
                OnDescriptionSpecialChanged();
            }
        }
        private global::System.String _DescriptionSpecial;
        partial void OnDescriptionSpecialChanging(global::System.String value);
        partial void OnDescriptionSpecialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoftwareExport
        {
            get
            {
                return _SoftwareExport;
            }
            set
            {
                OnSoftwareExportChanging(value);
                ReportPropertyChanging("SoftwareExport");
                _SoftwareExport = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoftwareExport");
                OnSoftwareExportChanged();
            }
        }
        private global::System.String _SoftwareExport;
        partial void OnSoftwareExportChanging(global::System.String value);
        partial void OnSoftwareExportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoftwareImport
        {
            get
            {
                return _SoftwareImport;
            }
            set
            {
                OnSoftwareImportChanging(value);
                ReportPropertyChanging("SoftwareImport");
                _SoftwareImport = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoftwareImport");
                OnSoftwareImportChanged();
            }
        }
        private global::System.String _SoftwareImport;
        partial void OnSoftwareImportChanging(global::System.String value);
        partial void OnSoftwareImportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoftwareNotes
        {
            get
            {
                return _SoftwareNotes;
            }
            set
            {
                OnSoftwareNotesChanging(value);
                ReportPropertyChanging("SoftwareNotes");
                _SoftwareNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoftwareNotes");
                OnSoftwareNotesChanged();
            }
        }
        private global::System.String _SoftwareNotes;
        partial void OnSoftwareNotesChanging(global::System.String value);
        partial void OnSoftwareNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RelatedModel
        {
            get
            {
                return _RelatedModel;
            }
            set
            {
                OnRelatedModelChanging(value);
                ReportPropertyChanging("RelatedModel");
                _RelatedModel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RelatedModel");
                OnRelatedModelChanged();
            }
        }
        private global::System.String _RelatedModel;
        partial void OnRelatedModelChanging(global::System.String value);
        partial void OnRelatedModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean OfInterest
        {
            get
            {
                return _OfInterest;
            }
            set
            {
                OnOfInterestChanging(value);
                ReportPropertyChanging("OfInterest");
                _OfInterest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OfInterest");
                OnOfInterestChanged();
            }
        }
        private global::System.Boolean _OfInterest;
        partial void OnOfInterestChanging(global::System.Boolean value);
        partial void OnOfInterestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Boolean _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Boolean value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NameSpaceGuid
        {
            get
            {
                return _NameSpaceGuid;
            }
            set
            {
                OnNameSpaceGuidChanging(value);
                ReportPropertyChanging("NameSpaceGuid");
                _NameSpaceGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NameSpaceGuid");
                OnNameSpaceGuidChanged();
            }
        }
        private global::System.Guid _NameSpaceGuid;
        partial void OnNameSpaceGuidChanging(global::System.Guid value);
        partial void OnNameSpaceGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "NameSpaceAciExchange", "NameSpace")]
        public NameSpace NameSpace
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NameSpace>("BlackBox.NameSpaceAciExchange", "NameSpace").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NameSpace>("BlackBox.NameSpaceAciExchange", "NameSpace").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NameSpace> NameSpaceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NameSpace>("BlackBox.NameSpaceAciExchange", "NameSpace");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NameSpace>("BlackBox.NameSpaceAciExchange", "NameSpace", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "AciExchangeMvdDefinition", "MvdDefinition")]
        public EntityCollection<MvdDefinition> MvdDefinitions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MvdDefinition>("BlackBox.AciExchangeMvdDefinition", "MvdDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MvdDefinition>("BlackBox.AciExchangeMvdDefinition", "MvdDefinition", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="NameSpace")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NameSpace : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NameSpace object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static NameSpace CreateNameSpace(global::System.Guid guid, global::System.String name)
        {
            NameSpace nameSpace = new NameSpace();
            nameSpace.Guid = guid;
            nameSpace.Name = name;
            return nameSpace;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "NameSpaceAciExchange", "AciExchange")]
        public EntityCollection<MvdExchange> MvdExchanges
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MvdExchange>("BlackBox.NameSpaceAciExchange", "AciExchange");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MvdExchange>("BlackBox.NameSpaceAciExchange", "AciExchange", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbDefinitionNameSpace", "BbDefinition")]
        public EntityCollection<BbDefinition> BbDefinitions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbDefinition>("BlackBox.BbDefinitionNameSpace", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbDefinition>("BlackBox.BbDefinitionNameSpace", "BbDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "BbDefinitionNameSpace1", "BbDefinition")]
        public EntityCollection<BbDefinition> RootBbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbDefinition>("BlackBox.BbDefinitionNameSpace1", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbDefinition>("BlackBox.BbDefinitionNameSpace1", "BbDefinition", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlackBox", Name="SEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SEntity : Definition
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SEntity object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static SEntity CreateSEntity(global::System.Guid guid, global::System.String name)
        {
            SEntity sEntity = new SEntity();
            sEntity.Guid = guid;
            sEntity.Name = name;
            return sEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Schema
        {
            get
            {
                return _Schema;
            }
            set
            {
                OnSchemaChanging(value);
                ReportPropertyChanging("Schema");
                _Schema = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Schema");
                OnSchemaChanged();
            }
        }
        private global::System.String _Schema = "2x3";
        partial void OnSchemaChanging(global::System.String value);
        partial void OnSchemaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "SEntityBbDefinition", "BbDefinition")]
        public EntityCollection<BbDefinition> BbDefinitions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BbDefinition>("BlackBox.SEntityBbDefinition", "BbDefinition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BbDefinition>("BlackBox.SEntityBbDefinition", "BbDefinition", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlackBox", "EntityAttributeSEntity", "EntityAttribute")]
        public EntityCollection<EntityAttribute> EntityAttributes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityAttribute>("BlackBox.EntityAttributeSEntity", "EntityAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityAttribute>("BlackBox.EntityAttributeSEntity", "EntityAttribute", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
